# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3"  # last stable CPython version

# Build documentation in the doc/arm/ directory with Sphinx
sphinx:
   configuration: doc/arm/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats: all

python:
   install:
     - requirements: doc/arm/requirements.txt

# disable server-side search as it gives worse results than Sphinx built-in
search:
  ignore:
    - "*"
